#ifndef ASM_H
#error "ERROR - PLEASE DON'T USE THIS LIBRARY DIRECTLY!!!"
#endif /* !ASM_H */

/* ************************ [v] 64-BIT REGISTERS [v] ************************ */
#define SBB_RAX_RAX sbb rax, rax
#define SBB_RAX_RBX sbb rax, rbx
#define SBB_RAX_RCX sbb rax, rcx
#define SBB_RAX_RDX sbb rax, rdx
#define SBB_RAX_RDI sbb rax, rdi
#define SBB_RAX_RSI sbb rax, rsi
#define SBB_RAX_RBP sbb rax, rbp
#define SBB_RAX_RSP sbb rax, rsp
#define SBB_RAX_R8 sbb rax, r8
#define SBB_RAX_R9 sbb rax, r9
#define SBB_RAX_R10 sbb rax, r10
#define SBB_RAX_R11 sbb rax, r11
#define SBB_RAX_R12 sbb rax, r12
#define SBB_RAX_R13 sbb rax, r13
#define SBB_RAX_R14 sbb rax, r14
#define SBB_RAX_R15 sbb rax, r15

#define SBB_RBX_RAX sbb rbx, rax
#define SBB_RBX_RBX sbb rbx, rbx
#define SBB_RBX_RCX sbb rbx, rcx
#define SBB_RBX_RDX sbb rbx, rdx
#define SBB_RBX_RDI sbb rbx, rdi
#define SBB_RBX_RSI sbb rbx, rsi
#define SBB_RBX_RBP sbb rbx, rbp
#define SBB_RBX_RSP sbb rbx, rsp
#define SBB_RBX_R8 sbb rbx, r8
#define SBB_RBX_R9 sbb rbx, r9
#define SBB_RBX_R10 sbb rbx, r10
#define SBB_RBX_R11 sbb rbx, r11
#define SBB_RBX_R12 sbb rbx, r12
#define SBB_RBX_R13 sbb rbx, r13
#define SBB_RBX_R14 sbb rbx, r14
#define SBB_RBX_R15 sbb rbx, r15

#define SBB_RCX_RAX sbb rcx, rax
#define SBB_RCX_RBX sbb rcx, rbx
#define SBB_RCX_RCX sbb rcx, rcx
#define SBB_RCX_RDX sbb rcx, rdx
#define SBB_RCX_RDI sbb rcx, rdi
#define SBB_RCX_RSI sbb rcx, rsi
#define SBB_RCX_RBP sbb rcx, rbp
#define SBB_RCX_RSP sbb rcx, rsp
#define SBB_RCX_R8 sbb rcx, r8
#define SBB_RCX_R9 sbb rcx, r9
#define SBB_RCX_R10 sbb rcx, r10
#define SBB_RCX_R11 sbb rcx, r11
#define SBB_RCX_R12 sbb rcx, r12
#define SBB_RCX_R13 sbb rcx, r13
#define SBB_RCX_R14 sbb rcx, r14
#define SBB_RCX_R15 sbb rcx, r15

#define SBB_RDX_RAX sbb rdx, rax
#define SBB_RDX_RBX sbb rdx, rbx
#define SBB_RDX_RCX sbb rdx, rcx
#define SBB_RDX_RDX sbb rdx, rdx
#define SBB_RDX_RDI sbb rdx, rdi
#define SBB_RDX_RSI sbb rdx, rsi
#define SBB_RDX_RBP sbb rdx, rbp
#define SBB_RDX_RSP sbb rdx, rsp
#define SBB_RDX_R8 sbb rdx, r8
#define SBB_RDX_R9 sbb rdx, r9
#define SBB_RDX_R10 sbb rdx, r10
#define SBB_RDX_R11 sbb rdx, r11
#define SBB_RDX_R12 sbb rdx, r12
#define SBB_RDX_R13 sbb rdx, r13
#define SBB_RDX_R14 sbb rdx, r14
#define SBB_RDX_R15 sbb rdx, r15

#define SBB_RDI_RAX sbb rdi, rax
#define SBB_RDI_RBX sbb rdi, rbx
#define SBB_RDI_RCX sbb rdi, rcx
#define SBB_RDI_RDX sbb rdi, rdx
#define SBB_RDI_RDI sbb rdi, rdi
#define SBB_RDI_RSI sbb rdi, rsi
#define SBB_RDI_RBP sbb rdi, rbp
#define SBB_RDI_RSP sbb rdi, rsp
#define SBB_RDI_R8 sbb rdi, r8
#define SBB_RDI_R9 sbb rdi, r9
#define SBB_RDI_R10 sbb rdi, r10
#define SBB_RDI_R11 sbb rdi, r11
#define SBB_RDI_R12 sbb rdi, r12
#define SBB_RDI_R13 sbb rdi, r13
#define SBB_RDI_R14 sbb rdi, r14
#define SBB_RDI_R15 sbb rdi, r15

#define SBB_RSI_RAX sbb rsi, rax
#define SBB_RSI_RBX sbb rsi, rbx
#define SBB_RSI_RCX sbb rsi, rcx
#define SBB_RSI_RDX sbb rsi, rdx
#define SBB_RSI_RDI sbb rsi, rdi
#define SBB_RSI_RSI sbb rsi, rsi
#define SBB_RSI_RBP sbb rsi, rbp
#define SBB_RSI_RSP sbb rsi, rsp
#define SBB_RSI_R8 sbb rsi, r8
#define SBB_RSI_R9 sbb rsi, r9
#define SBB_RSI_R10 sbb rsi, r10
#define SBB_RSI_R11 sbb rsi, r11
#define SBB_RSI_R12 sbb rsi, r12
#define SBB_RSI_R13 sbb rsi, r13
#define SBB_RSI_R14 sbb rsi, r14
#define SBB_RSI_R15 sbb rsi, r15

#define SBB_RBP_RAX sbb rbp, rax
#define SBB_RBP_RBX sbb rbp, rbx
#define SBB_RBP_RCX sbb rbp, rcx
#define SBB_RBP_RDX sbb rbp, rdx
#define SBB_RBP_RDI sbb rbp, rdi
#define SBB_RBP_RSI sbb rbp, rsi
#define SBB_RBP_RBP sbb rbp, rbp
#define SBB_RBP_RSP sbb rbp, rsp
#define SBB_RBP_R8 sbb rbp, r8
#define SBB_RBP_R9 sbb rbp, r9
#define SBB_RBP_R10 sbb rbp, r10
#define SBB_RBP_R11 sbb rbp, r11
#define SBB_RBP_R12 sbb rbp, r12
#define SBB_RBP_R13 sbb rbp, r13
#define SBB_RBP_R14 sbb rbp, r14
#define SBB_RBP_R15 sbb rbp, r15

#define SBB_RSP_RAX sbb rsp, rax
#define SBB_RSP_RBX sbb rsp, rbx
#define SBB_RSP_RCX sbb rsp, rcx
#define SBB_RSP_RDX sbb rsp, rdx
#define SBB_RSP_RDI sbb rsp, rdi
#define SBB_RSP_RSI sbb rsp, rsi
#define SBB_RSP_RBP sbb rsp, rbp
#define SBB_RSP_RSP sbb rsp, rsp
#define SBB_RSP_R8 sbb rsp, r8
#define SBB_RSP_R9 sbb rsp, r9
#define SBB_RSP_R10 sbb rsp, r10
#define SBB_RSP_R11 sbb rsp, r11
#define SBB_RSP_R12 sbb rsp, r12
#define SBB_RSP_R13 sbb rsp, r13
#define SBB_RSP_R14 sbb rsp, r14
#define SBB_RSP_R15 sbb rsp, r15

#define SBB_R8_RAX sbb r8, rax
#define SBB_R8_RBX sbb r8, rbx
#define SBB_R8_RCX sbb r8, rcx
#define SBB_R8_RDX sbb r8, rdx
#define SBB_R8_RDI sbb r8, rdi
#define SBB_R8_RSI sbb r8, rsi
#define SBB_R8_RBP sbb r8, rbp
#define SBB_R8_RSP sbb r8, rsp
#define SBB_R8_R8 sbb r8, r8
#define SBB_R8_R9 sbb r8, r9
#define SBB_R8_R10 sbb r8, r10
#define SBB_R8_R11 sbb r8, r11
#define SBB_R8_R12 sbb r8, r12
#define SBB_R8_R13 sbb r8, r13
#define SBB_R8_R14 sbb r8, r14
#define SBB_R8_R15 sbb r8, r15

#define SBB_R9_RAX sbb r9, rax
#define SBB_R9_RBX sbb r9, rbx
#define SBB_R9_RCX sbb r9, rcx
#define SBB_R9_RDX sbb r9, rdx
#define SBB_R9_RDI sbb r9, rdi
#define SBB_R9_RSI sbb r9, rsi
#define SBB_R9_RBP sbb r9, rbp
#define SBB_R9_RSP sbb r9, rsp
#define SBB_R9_R8 sbb r9, r8
#define SBB_R9_R9 sbb r9, r9
#define SBB_R9_R10 sbb r9, r10
#define SBB_R9_R11 sbb r9, r11
#define SBB_R9_R12 sbb r9, r12
#define SBB_R9_R13 sbb r9, r13
#define SBB_R9_R14 sbb r9, r14
#define SBB_R9_R15 sbb r9, r15

#define SBB_R10_RAX sbb r10, rax
#define SBB_R10_RBX sbb r10, rbx
#define SBB_R10_RCX sbb r10, rcx
#define SBB_R10_RDX sbb r10, rdx
#define SBB_R10_RDI sbb r10, rdi
#define SBB_R10_RSI sbb r10, rsi
#define SBB_R10_RBP sbb r10, rbp
#define SBB_R10_RSP sbb r10, rsp
#define SBB_R10_R8 sbb r10, r8
#define SBB_R10_R9 sbb r10, r9
#define SBB_R10_R10 sbb r10, r10
#define SBB_R10_R11 sbb r10, r11
#define SBB_R10_R12 sbb r10, r12
#define SBB_R10_R13 sbb r10, r13
#define SBB_R10_R14 sbb r10, r14
#define SBB_R10_R15 sbb r10, r15

#define SBB_R11_RAX sbb r11, rax
#define SBB_R11_RBX sbb r11, rbx
#define SBB_R11_RCX sbb r11, rcx
#define SBB_R11_RDX sbb r11, rdx
#define SBB_R11_RDI sbb r11, rdi
#define SBB_R11_RSI sbb r11, rsi
#define SBB_R11_RBP sbb r11, rbp
#define SBB_R11_RSP sbb r11, rsp
#define SBB_R11_R8 sbb r11, r8
#define SBB_R11_R9 sbb r11, r9
#define SBB_R11_R10 sbb r11, r10
#define SBB_R11_R11 sbb r11, r11
#define SBB_R11_R12 sbb r11, r12
#define SBB_R11_R13 sbb r11, r13
#define SBB_R11_R14 sbb r11, r14
#define SBB_R11_R15 sbb r11, r15

#define SBB_R12_RAX sbb r12, rax
#define SBB_R12_RBX sbb r12, rbx
#define SBB_R12_RCX sbb r12, rcx
#define SBB_R12_RDX sbb r12, rdx
#define SBB_R12_RDI sbb r12, rdi
#define SBB_R12_RSI sbb r12, rsi
#define SBB_R12_RBP sbb r12, rbp
#define SBB_R12_RSP sbb r12, rsp
#define SBB_R12_R8 sbb r12, r8
#define SBB_R12_R9 sbb r12, r9
#define SBB_R12_R10 sbb r12, r10
#define SBB_R12_R11 sbb r12, r11
#define SBB_R12_R12 sbb r12, r12
#define SBB_R12_R13 sbb r12, r13
#define SBB_R12_R14 sbb r12, r14
#define SBB_R12_R15 sbb r12, r15

#define SBB_R13_RAX sbb r13, rax
#define SBB_R13_RBX sbb r13, rbx
#define SBB_R13_RCX sbb r13, rcx
#define SBB_R13_RDX sbb r13, rdx
#define SBB_R13_RDI sbb r13, rdi
#define SBB_R13_RSI sbb r13, rsi
#define SBB_R13_RBP sbb r13, rbp
#define SBB_R13_RSP sbb r13, rsp
#define SBB_R13_R8 sbb r13, r8
#define SBB_R13_R9 sbb r13, r9
#define SBB_R13_R10 sbb r13, r10
#define SBB_R13_R11 sbb r13, r11
#define SBB_R13_R12 sbb r13, r12
#define SBB_R13_R13 sbb r13, r13
#define SBB_R13_R14 sbb r13, r14
#define SBB_R13_R15 sbb r13, r15

#define SBB_R14_RAX sbb r14, rax
#define SBB_R14_RBX sbb r14, rbx
#define SBB_R14_RCX sbb r14, rcx
#define SBB_R14_RDX sbb r14, rdx
#define SBB_R14_RDI sbb r14, rdi
#define SBB_R14_RSI sbb r14, rsi
#define SBB_R14_RBP sbb r14, rbp
#define SBB_R14_RSP sbb r14, rsp
#define SBB_R14_R8 sbb r14, r8
#define SBB_R14_R9 sbb r14, r9
#define SBB_R14_R10 sbb r14, r10
#define SBB_R14_R11 sbb r14, r11
#define SBB_R14_R12 sbb r14, r12
#define SBB_R14_R13 sbb r14, r13
#define SBB_R14_R14 sbb r14, r14
#define SBB_R14_R15 sbb r14, r15

#define SBB_R15_RAX sbb r15, rax
#define SBB_R15_RBX sbb r15, rbx
#define SBB_R15_RCX sbb r15, rcx
#define SBB_R15_RDX sbb r15, rdx
#define SBB_R15_RDI sbb r15, rdi
#define SBB_R15_RSI sbb r15, rsi
#define SBB_R15_RBP sbb r15, rbp
#define SBB_R15_RSP sbb r15, rsp
#define SBB_R15_R8 sbb r15, r8
#define SBB_R15_R9 sbb r15, r9
#define SBB_R15_R10 sbb r15, r10
#define SBB_R15_R11 sbb r15, r11
#define SBB_R15_R12 sbb r15, r12
#define SBB_R15_R13 sbb r15, r13
#define SBB_R15_R14 sbb r15, r14
#define SBB_R15_R15 sbb r15, r15

#define SBB_RAX_(VALUE) sbb rax, VALUE
#define SBB_RBX_(VALUE) sbb rbx, VALUE
#define SBB_RCX_(VALUE) sbb rcx, VALUE
#define SBB_RDX_(VALUE) sbb rdx, VALUE
#define SBB_RDI_(VALUE) sbb rdi, VALUE
#define SBB_RSI_(VALUE) sbb rsi, VALUE
#define SBB_RBP_(VALUE) sbb rbp, VALUE
#define SBB_RSP_(VALUE) sbb rsp, VALUE
#define SBB_R8_(VALUE) sbb r8, VALUE
#define SBB_R9_(VALUE) sbb r9, VALUE
#define SBB_R10_(VALUE) sbb r10, VALUE
#define SBB_R11_(VALUE) sbb r11, VALUE
#define SBB_R12_(VALUE) sbb r12, VALUE
#define SBB_R13_(VALUE) sbb r13, VALUE
#define SBB_R14_(VALUE) sbb r14, VALUE
#define SBB_R15_(VALUE) sbb r15, VALUE
/* ************************ [^] 64-BIT REGISTERS [^] ************************ */

#include "32.INL"

/* * * * * * * * * * * /!\ AUTOMATIC EOF TREATMENT! /!\ * * * * * * * * * * * *\
 * * AT THE ALL END OF FILES, I AM ADDING A SPECIAL BYTE <0X1A> TO END THE  * *
 * *                       FILE IN DOS, CP/M SYSTEMS                        * *
 * *   "//" FOR HANDLING THE BYTE IN MODERN COMPILERS AND #define IS FOR    * *
 * *       HANDLING "//" SYNTAX WHICH IS NOT SUPPORTED ON OLD SYSTEMS       * *
\* * * * * * * * * * * * * * * * * * *  * * * * * * * * * * * * * * * * * * * */
#undef __CMT__END_OF_FILE__
#define __CMT__END_OF_FILE__ //
