#ifndef ASM_H
#error "ERROR - PLEASE DON'T USE THIS LIBRARY DIRECTLY!!!"
#endif /* !ASM_H */

/* ************************ [v] 64-BIT REGISTERS [v] ************************ */
#define ADC_RAX_RAX adc rax, rax
#define ADC_RAX_RBX adc rax, rbx
#define ADC_RAX_RCX adc rax, rcx
#define ADC_RAX_RDX adc rax, rdx
#define ADC_RAX_RDI adc rax, rdi
#define ADC_RAX_RSI adc rax, rsi
#define ADC_RAX_RBP adc rax, rbp
#define ADC_RAX_RSP adc rax, rsp
#define ADC_RAX_R8 adc rax, r8
#define ADC_RAX_R9 adc rax, r9
#define ADC_RAX_R10 adc rax, r10
#define ADC_RAX_R11 adc rax, r11
#define ADC_RAX_R12 adc rax, r12
#define ADC_RAX_R13 adc rax, r13
#define ADC_RAX_R14 adc rax, r14
#define ADC_RAX_R15 adc rax, r15

#define ADC_RBX_RAX adc rbx, rax
#define ADC_RBX_RBX adc rbx, rbx
#define ADC_RBX_RCX adc rbx, rcx
#define ADC_RBX_RDX adc rbx, rdx
#define ADC_RBX_RDI adc rbx, rdi
#define ADC_RBX_RSI adc rbx, rsi
#define ADC_RBX_RBP adc rbx, rbp
#define ADC_RBX_RSP adc rbx, rsp
#define ADC_RBX_R8 adc rbx, r8
#define ADC_RBX_R9 adc rbx, r9
#define ADC_RBX_R10 adc rbx, r10
#define ADC_RBX_R11 adc rbx, r11
#define ADC_RBX_R12 adc rbx, r12
#define ADC_RBX_R13 adc rbx, r13
#define ADC_RBX_R14 adc rbx, r14
#define ADC_RBX_R15 adc rbx, r15

#define ADC_RCX_RAX adc rcx, rax
#define ADC_RCX_RBX adc rcx, rbx
#define ADC_RCX_RCX adc rcx, rcx
#define ADC_RCX_RDX adc rcx, rdx
#define ADC_RCX_RDI adc rcx, rdi
#define ADC_RCX_RSI adc rcx, rsi
#define ADC_RCX_RBP adc rcx, rbp
#define ADC_RCX_RSP adc rcx, rsp
#define ADC_RCX_R8 adc rcx, r8
#define ADC_RCX_R9 adc rcx, r9
#define ADC_RCX_R10 adc rcx, r10
#define ADC_RCX_R11 adc rcx, r11
#define ADC_RCX_R12 adc rcx, r12
#define ADC_RCX_R13 adc rcx, r13
#define ADC_RCX_R14 adc rcx, r14
#define ADC_RCX_R15 adc rcx, r15

#define ADC_RDX_RAX adc rdx, rax
#define ADC_RDX_RBX adc rdx, rbx
#define ADC_RDX_RCX adc rdx, rcx
#define ADC_RDX_RDX adc rdx, rdx
#define ADC_RDX_RDI adc rdx, rdi
#define ADC_RDX_RSI adc rdx, rsi
#define ADC_RDX_RBP adc rdx, rbp
#define ADC_RDX_RSP adc rdx, rsp
#define ADC_RDX_R8 adc rdx, r8
#define ADC_RDX_R9 adc rdx, r9
#define ADC_RDX_R10 adc rdx, r10
#define ADC_RDX_R11 adc rdx, r11
#define ADC_RDX_R12 adc rdx, r12
#define ADC_RDX_R13 adc rdx, r13
#define ADC_RDX_R14 adc rdx, r14
#define ADC_RDX_R15 adc rdx, r15

#define ADC_RDI_RAX adc rdi, rax
#define ADC_RDI_RBX adc rdi, rbx
#define ADC_RDI_RCX adc rdi, rcx
#define ADC_RDI_RDX adc rdi, rdx
#define ADC_RDI_RDI adc rdi, rdi
#define ADC_RDI_RSI adc rdi, rsi
#define ADC_RDI_RBP adc rdi, rbp
#define ADC_RDI_RSP adc rdi, rsp
#define ADC_RDI_R8 adc rdi, r8
#define ADC_RDI_R9 adc rdi, r9
#define ADC_RDI_R10 adc rdi, r10
#define ADC_RDI_R11 adc rdi, r11
#define ADC_RDI_R12 adc rdi, r12
#define ADC_RDI_R13 adc rdi, r13
#define ADC_RDI_R14 adc rdi, r14
#define ADC_RDI_R15 adc rdi, r15

#define ADC_RSI_RAX adc rsi, rax
#define ADC_RSI_RBX adc rsi, rbx
#define ADC_RSI_RCX adc rsi, rcx
#define ADC_RSI_RDX adc rsi, rdx
#define ADC_RSI_RDI adc rsi, rdi
#define ADC_RSI_RSI adc rsi, rsi
#define ADC_RSI_RBP adc rsi, rbp
#define ADC_RSI_RSP adc rsi, rsp
#define ADC_RSI_R8 adc rsi, r8
#define ADC_RSI_R9 adc rsi, r9
#define ADC_RSI_R10 adc rsi, r10
#define ADC_RSI_R11 adc rsi, r11
#define ADC_RSI_R12 adc rsi, r12
#define ADC_RSI_R13 adc rsi, r13
#define ADC_RSI_R14 adc rsi, r14
#define ADC_RSI_R15 adc rsi, r15

#define ADC_RBP_RAX adc rbp, rax
#define ADC_RBP_RBX adc rbp, rbx
#define ADC_RBP_RCX adc rbp, rcx
#define ADC_RBP_RDX adc rbp, rdx
#define ADC_RBP_RDI adc rbp, rdi
#define ADC_RBP_RSI adc rbp, rsi
#define ADC_RBP_RBP adc rbp, rbp
#define ADC_RBP_RSP adc rbp, rsp
#define ADC_RBP_R8 adc rbp, r8
#define ADC_RBP_R9 adc rbp, r9
#define ADC_RBP_R10 adc rbp, r10
#define ADC_RBP_R11 adc rbp, r11
#define ADC_RBP_R12 adc rbp, r12
#define ADC_RBP_R13 adc rbp, r13
#define ADC_RBP_R14 adc rbp, r14
#define ADC_RBP_R15 adc rbp, r15

#define ADC_RSP_RAX adc rsp, rax
#define ADC_RSP_RBX adc rsp, rbx
#define ADC_RSP_RCX adc rsp, rcx
#define ADC_RSP_RDX adc rsp, rdx
#define ADC_RSP_RDI adc rsp, rdi
#define ADC_RSP_RSI adc rsp, rsi
#define ADC_RSP_RBP adc rsp, rbp
#define ADC_RSP_RSP adc rsp, rsp
#define ADC_RSP_R8 adc rsp, r8
#define ADC_RSP_R9 adc rsp, r9
#define ADC_RSP_R10 adc rsp, r10
#define ADC_RSP_R11 adc rsp, r11
#define ADC_RSP_R12 adc rsp, r12
#define ADC_RSP_R13 adc rsp, r13
#define ADC_RSP_R14 adc rsp, r14
#define ADC_RSP_R15 adc rsp, r15

#define ADC_R8_RAX adc r8, rax
#define ADC_R8_RBX adc r8, rbx
#define ADC_R8_RCX adc r8, rcx
#define ADC_R8_RDX adc r8, rdx
#define ADC_R8_RDI adc r8, rdi
#define ADC_R8_RSI adc r8, rsi
#define ADC_R8_RBP adc r8, rbp
#define ADC_R8_RSP adc r8, rsp
#define ADC_R8_R8 adc r8, r8
#define ADC_R8_R9 adc r8, r9
#define ADC_R8_R10 adc r8, r10
#define ADC_R8_R11 adc r8, r11
#define ADC_R8_R12 adc r8, r12
#define ADC_R8_R13 adc r8, r13
#define ADC_R8_R14 adc r8, r14
#define ADC_R8_R15 adc r8, r15

#define ADC_R9_RAX adc r9, rax
#define ADC_R9_RBX adc r9, rbx
#define ADC_R9_RCX adc r9, rcx
#define ADC_R9_RDX adc r9, rdx
#define ADC_R9_RDI adc r9, rdi
#define ADC_R9_RSI adc r9, rsi
#define ADC_R9_RBP adc r9, rbp
#define ADC_R9_RSP adc r9, rsp
#define ADC_R9_R8 adc r9, r8
#define ADC_R9_R9 adc r9, r9
#define ADC_R9_R10 adc r9, r10
#define ADC_R9_R11 adc r9, r11
#define ADC_R9_R12 adc r9, r12
#define ADC_R9_R13 adc r9, r13
#define ADC_R9_R14 adc r9, r14
#define ADC_R9_R15 adc r9, r15

#define ADC_R10_RAX adc r10, rax
#define ADC_R10_RBX adc r10, rbx
#define ADC_R10_RCX adc r10, rcx
#define ADC_R10_RDX adc r10, rdx
#define ADC_R10_RDI adc r10, rdi
#define ADC_R10_RSI adc r10, rsi
#define ADC_R10_RBP adc r10, rbp
#define ADC_R10_RSP adc r10, rsp
#define ADC_R10_R8 adc r10, r8
#define ADC_R10_R9 adc r10, r9
#define ADC_R10_R10 adc r10, r10
#define ADC_R10_R11 adc r10, r11
#define ADC_R10_R12 adc r10, r12
#define ADC_R10_R13 adc r10, r13
#define ADC_R10_R14 adc r10, r14
#define ADC_R10_R15 adc r10, r15

#define ADC_R11_RAX adc r11, rax
#define ADC_R11_RBX adc r11, rbx
#define ADC_R11_RCX adc r11, rcx
#define ADC_R11_RDX adc r11, rdx
#define ADC_R11_RDI adc r11, rdi
#define ADC_R11_RSI adc r11, rsi
#define ADC_R11_RBP adc r11, rbp
#define ADC_R11_RSP adc r11, rsp
#define ADC_R11_R8 adc r11, r8
#define ADC_R11_R9 adc r11, r9
#define ADC_R11_R10 adc r11, r10
#define ADC_R11_R11 adc r11, r11
#define ADC_R11_R12 adc r11, r12
#define ADC_R11_R13 adc r11, r13
#define ADC_R11_R14 adc r11, r14
#define ADC_R11_R15 adc r11, r15

#define ADC_R12_RAX adc r12, rax
#define ADC_R12_RBX adc r12, rbx
#define ADC_R12_RCX adc r12, rcx
#define ADC_R12_RDX adc r12, rdx
#define ADC_R12_RDI adc r12, rdi
#define ADC_R12_RSI adc r12, rsi
#define ADC_R12_RBP adc r12, rbp
#define ADC_R12_RSP adc r12, rsp
#define ADC_R12_R8 adc r12, r8
#define ADC_R12_R9 adc r12, r9
#define ADC_R12_R10 adc r12, r10
#define ADC_R12_R11 adc r12, r11
#define ADC_R12_R12 adc r12, r12
#define ADC_R12_R13 adc r12, r13
#define ADC_R12_R14 adc r12, r14
#define ADC_R12_R15 adc r12, r15

#define ADC_R13_RAX adc r13, rax
#define ADC_R13_RBX adc r13, rbx
#define ADC_R13_RCX adc r13, rcx
#define ADC_R13_RDX adc r13, rdx
#define ADC_R13_RDI adc r13, rdi
#define ADC_R13_RSI adc r13, rsi
#define ADC_R13_RBP adc r13, rbp
#define ADC_R13_RSP adc r13, rsp
#define ADC_R13_R8 adc r13, r8
#define ADC_R13_R9 adc r13, r9
#define ADC_R13_R10 adc r13, r10
#define ADC_R13_R11 adc r13, r11
#define ADC_R13_R12 adc r13, r12
#define ADC_R13_R13 adc r13, r13
#define ADC_R13_R14 adc r13, r14
#define ADC_R13_R15 adc r13, r15

#define ADC_R14_RAX adc r14, rax
#define ADC_R14_RBX adc r14, rbx
#define ADC_R14_RCX adc r14, rcx
#define ADC_R14_RDX adc r14, rdx
#define ADC_R14_RDI adc r14, rdi
#define ADC_R14_RSI adc r14, rsi
#define ADC_R14_RBP adc r14, rbp
#define ADC_R14_RSP adc r14, rsp
#define ADC_R14_R8 adc r14, r8
#define ADC_R14_R9 adc r14, r9
#define ADC_R14_R10 adc r14, r10
#define ADC_R14_R11 adc r14, r11
#define ADC_R14_R12 adc r14, r12
#define ADC_R14_R13 adc r14, r13
#define ADC_R14_R14 adc r14, r14
#define ADC_R14_R15 adc r14, r15

#define ADC_R15_RAX adc r15, rax
#define ADC_R15_RBX adc r15, rbx
#define ADC_R15_RCX adc r15, rcx
#define ADC_R15_RDX adc r15, rdx
#define ADC_R15_RDI adc r15, rdi
#define ADC_R15_RSI adc r15, rsi
#define ADC_R15_RBP adc r15, rbp
#define ADC_R15_RSP adc r15, rsp
#define ADC_R15_R8 adc r15, r8
#define ADC_R15_R9 adc r15, r9
#define ADC_R15_R10 adc r15, r10
#define ADC_R15_R11 adc r15, r11
#define ADC_R15_R12 adc r15, r12
#define ADC_R15_R13 adc r15, r13
#define ADC_R15_R14 adc r15, r14
#define ADC_R15_R15 adc r15, r15

#define ADC_RAX_(VALUE) adc rax, VALUE
#define ADC_RBX_(VALUE) adc rbx, VALUE
#define ADC_RCX_(VALUE) adc rcx, VALUE
#define ADC_RDX_(VALUE) adc rdx, VALUE
#define ADC_RDI_(VALUE) adc rdi, VALUE
#define ADC_RSI_(VALUE) adc rsi, VALUE
#define ADC_RBP_(VALUE) adc rbp, VALUE
#define ADC_RSP_(VALUE) adc rsp, VALUE
#define ADC_R8_(VALUE) adc r8, VALUE
#define ADC_R9_(VALUE) adc r9, VALUE
#define ADC_R10_(VALUE) adc r10, VALUE
#define ADC_R11_(VALUE) adc r11, VALUE
#define ADC_R12_(VALUE) adc r12, VALUE
#define ADC_R13_(VALUE) adc r13, VALUE
#define ADC_R14_(VALUE) adc r14, VALUE
#define ADC_R15_(VALUE) adc r15, VALUE
/* ************************ [^] 64-BIT REGISTERS [^] ************************ */

#include "32.INL"

/* * * * * * * * * * * /!\ AUTOMATIC EOF TREATMENT! /!\ * * * * * * * * * * * *\
 * * AT THE ALL END OF FILES, I AM ADDING A SPECIAL BYTE <0X1A> TO END THE  * *
 * *                       FILE IN DOS, CP/M SYSTEMS                        * *
 * *   "//" FOR HANDLING THE BYTE IN MODERN COMPILERS AND #define IS FOR    * *
 * *       HANDLING "//" SYNTAX WHICH IS NOT SUPPORTED ON OLD SYSTEMS       * *
\* * * * * * * * * * * * * * * * * * *  * * * * * * * * * * * * * * * * * * * */
#undef __CMT__END_OF_FILE__
#define __CMT__END_OF_FILE__ //
